# Pandas Test

# Vooaf:
Neem voldoende tijd om de dataset te verkennen voordat je met de eigenlijke opgave begint. Je moet de vragen niet in een bepaalde volgorde oplossen. Je kan dus een vraag overslaan wanneer je niet direct het antwoord weet. En vooral

<div style="width=100%;font-weight:90;font-size:16px;text-align:center">Don't Panic! </div>

# De dataset

Deze dataset bevat boekingsinformatie voor een stadshotel en een resort, en omvat informatie zoals wanneer de boeking is gemaakt, de verblijfsduur, het aantal volwassenen, kinderen en/of baby's, en het aantal beschikbare parkeerplaatsen, naast andere zaken.

Alle persoonlijk identificeerbare informatie is uit de data verwijderd.

De data komt oorspronkelijk uit het artikel ["Hotel Booking Demand Datasets"](https://www.sciencedirect.com/science/article/pii/S2352340918315191), geschreven door Nuno Antonio, Ana Almeida en Luis Nunes voor Data in Brief, Volume 22, februari 2019.


----------------------------

#### OPMERKING: Namen, e-mails, telefoonnummers en creditcardnummers in de data zijn synthetisch en geen echte informatie van mensen. Die kolommen vind je niet in het volgende overzicht. De hoteldata is echt en afkomstig uit de bovengenoemde publicatie.

## <div style="text-align: center">Gegevenskolommen</div>

<table><thead><tr class="rowsep-1"><th scope="col"><strong>Variable</strong></th><th scope="col"><strong>Type</strong></th><th scope="col"><strong>Omschrijving</strong></th><th scope="col"><strong>Bron/engineering</strong></th></tr></thead><tbody><tr><th scope="row"><em>ADR</em></th><td>Numeric</td><td>Average Daily Rate as defined by <a name="bbib5" href="#bib5" class="workspace-trigger">[5]</a></td><td>BO, BL and TR / Calculated by dividing the sum of all lodging transactions by the total number of staying nights</td></tr><tr><th scope="row"><em>Adults</em></th><td>Integer</td><td>Number of adults</td><td>BO and BL</td></tr><tr><th scope="row"><em>Agent</em></th><td>Categorical</td><td>ID of the travel agency that made the booking<a name="btbl1fna" href="#tbl1fna" class="workspace-trigger"><sup>a</sup></a></td><td>BO and BL</td></tr><tr><th scope="row"><em>ArrivalDateDayOfMonth</em></th><td>Integer</td><td>Day of the month of the arrival date</td><td>BO and BL</td></tr><tr><th scope="row"><em>ArrivalDateMonth</em></th><td>Categorical</td><td>Month of arrival date with 12 categories: “January” to “December”</td><td>BO and BL</td></tr><tr><th scope="row"><em>ArrivalDateWeekNumber</em></th><td>Integer</td><td>Week number of the arrival date</td><td>BO and BL</td></tr><tr><th scope="row"><em>ArrivalDateYear</em></th><td>Integer</td><td>Year of arrival date</td><td>BO and BL</td></tr><tr><th scope="row"><em>AssignedRoomType</em></th><td>Categorical</td><td>Code for the type of room assigned to the booking. Sometimes the assigned room type differs from the reserved room type due to hotel operation reasons (e.g. overbooking) or by customer request. Code is presented instead of designation for anonymity reasons</td><td>BO and BL</td></tr><tr><th scope="row"><em>Babies</em></th><td>Integer</td><td>Number of babies</td><td>BO and BL</td></tr><tr><th scope="row"><em>BookingChanges</em></th><td>Integer</td><td>Number of changes/amendments made to the booking from the moment the booking was entered on the PMS until the moment of check-in or cancellation</td><td>BO and BL/Calculated by adding the number of unique iterations that change some of the booking attributes, namely: persons, arrival date, nights, reserved room type or meal</td></tr><tr><th scope="row"><em>Children</em></th><td>Integer</td><td>Number of children</td><td>BO and BL/Sum of both payable and non-payable children</td></tr><tr><th scope="row"><em>Company</em></th><td>Categorical</td><td>ID of the company/entity that made the booking or responsible for paying the booking. ID is presented instead of designation for anonymity reasons</td><td>BO and BL.</td></tr><tr><th scope="row"><em>Country</em></th><td>Categorical</td><td>Country of origin. Categories are represented in the ISO 3155–3:2013 format <a name="bbib6" href="#bib6" class="workspace-trigger">[6]</a></td><td>BO, BL and NT</td></tr><tr><th scope="row"><br></th><td><br></td><td><br></td><td><br></td></tr><tr><th scope="row" rowspan="5"><em>CustomerType</em></th><td rowspan="5">Categorical</td><td>Type of booking, assuming one of four categories:</td><td rowspan="5">BO and BL</td></tr><tr><td>Contract - when the booking has an allotment or other type of contract associated to it;</td></tr><tr><td>Group – when the booking is associated to a group;</td></tr><tr><td>Transient – when the booking is not part of a group or contract, and is not associated to other transient booking;</td></tr><tr><td>Transient-party – when the booking is transient, but is associated to at least other transient booking</td></tr><tr><th scope="row"><em>DaysInWaitingList</em></th><td>Integer</td><td>Number of days the booking was in the waiting list before it was confirmed to the customer</td><td>BO/Calculated by subtracting the date the booking was confirmed to the customer from the date the booking entered on the PMS</td></tr><tr><th scope="row"><br></th><td><br></td><td><br></td><td><br></td></tr><tr><th scope="row" rowspan="7"><em>DepositType</em></th><td rowspan="7">Categorical</td><td>Indication on if the customer made a deposit to guarantee the booking. This variable can assume three categories:</td><td rowspan="2">BO and TR/Value calculated based on the payments identified for the booking in the transaction (TR) table before the booking׳s arrival or cancellation date.</td></tr><tr><td rowspan="3">No Deposit – no deposit was made;</td></tr><tr><td>In case no payments were found the value is “No Deposit”.</td></tr><tr><td rowspan="2">If the payment was equal or exceeded the total cost of stay, the value is set as “Non Refund”.</td></tr><tr><td rowspan="2">Non Refund – a deposit was made in the value of the total stay cost;</td></tr><tr><td rowspan="2">Otherwise the value is set as “Refundable”</td></tr><tr><td>Refundable – a deposit was made with a value under the total cost of stay.</td></tr><tr><th scope="row"><em>DistributionChannel</em></th><td>Categorical</td><td>Booking distribution channel. The term “TA” means “Travel Agents” and “TO” means “Tour Operators”</td><td>BO, BL and DC</td></tr><tr><th scope="row"><em>IsCanceled</em></th><td>Categorical</td><td>Value indicating if the booking was canceled (1) or not (0)</td><td>BO</td></tr><tr><th scope="row"><em>IsRepeatedGuest</em></th><td>Categorical</td><td>Value indicating if the booking name was from a repeated guest (1) or not (0)</td><td>BO, BL and C/ Variable created by verifying if a profile was associated with the booking customer. If so, and if the customer profile creation date was prior to the creation date for the booking on the PMS database it was assumed the booking was from a repeated guest</td></tr><tr><th scope="row"><em>LeadTime</em></th><td>Integer</td><td>Number of days that elapsed between the entering date of the booking into the PMS and the arrival date</td><td>BO and BL/ Subtraction of the entering date from the arrival date</td></tr><tr><th scope="row"><em>MarketSegment</em></th><td>Categorical</td><td>Market segment designation. In categories, the term “TA” means “Travel Agents” and “TO” means “Tour Operators”</td><td>BO, BL and MS</td></tr><tr><th scope="row"><br></th><td><br></td><td><br></td><td><br></td></tr><tr><th scope="row" rowspan="5"><em>Meal</em></th><td rowspan="5">Categorical</td><td>Type of meal booked. Categories are presented in standard hospitality meal packages:</td><td rowspan="5">BO, BL and ML</td></tr><tr><td>Undefined/SC – no meal package;</td></tr><tr><td>BB – Bed &amp; Breakfast;</td></tr><tr><td>HB – Half board (breakfast and one other meal – usually dinner);</td></tr><tr><td>FB – Full board (breakfast, lunch and dinner)</td></tr><tr><th scope="row"><em>PreviousBookingsNotCanceled</em></th><td>Integer</td><td>Number of previous bookings not cancelled by the customer prior to the current booking</td><td>BO and BL / In case there was no customer profile associated with the booking, the value is set to 0. Otherwise, the value is the number of bookings with the same customer profile created before the current booking and not canceled.</td></tr><tr><th scope="row"><em>PreviousCancellations</em></th><td>Integer</td><td>Number of previous bookings that were cancelled by the customer prior to the current booking</td><td>BO and BL/ In case there was no customer profile associated with the booking, the value is set to 0. Otherwise, the value is the number of bookings with the same customer profile created before the current booking and canceled.</td></tr><tr><th scope="row"><em>RequiredCardParkingSpaces</em></th><td>Integer</td><td>Number of car parking spaces required by the customer</td><td>BO and BL</td></tr><tr><th scope="row"><br></th><td><br></td><td><br></td><td><br></td></tr><tr><th scope="row" rowspan="4"><em>ReservationStatus</em></th><td rowspan="4">Categorical</td><td>Reservation last status, assuming one of three categories:</td><td rowspan="4">BO</td></tr><tr><td>Canceled – booking was canceled by the customer;</td></tr><tr><td>Check-Out – customer has checked in but already departed;</td></tr><tr><td>No-Show – customer did not check-in and did inform the hotel of the reason why</td></tr><tr><th scope="row"><em>ReservationStatusDate</em></th><td>Date</td><td>Date at which the last status was set. This variable can be used in conjunction with the <em>ReservationStatus</em> to understand when was the booking canceled or when did the customer checked-out of the hotel</td><td>BO</td></tr><tr><th scope="row"><em>ReservedRoomType</em></th><td>Categorical</td><td>Code of room type reserved. Code is presented instead of designation for anonymity reasons</td><td>BO and BL</td></tr><tr><th scope="row"><em>StaysInWeekendNights</em></th><td>Integer</td><td>Number of weekend nights (Saturday or Sunday) the guest stayed or booked to stay at the hotel</td><td>BO and BL/ Calculated by counting the number of weekend nights from the total number of nights</td></tr><tr><th scope="row"><em>StaysInWeekNights</em></th><td>Integer</td><td>Number of week nights (Monday to Friday) the guest stayed or booked to stay at the hotel</td><td>BO and BL/Calculated by counting the number of week nights from the total number of nights</td></tr><tr><th scope="row"><em>TotalOfSpecialRequests</em></th><td>Integer</td><td>Number of special requests made by the customer (e.g. twin bed or high floor)</td><td>BO and BL/Sum of all special requests</td></tr></tbody></table>

-----------

# TAKEN

**Voer de onderstaande taken uit die vetgedrukt zijn weergegeven. De verwachte output wordt weergegeven in een cel eronder. Let op: voer de cel boven de verwachte output niet uit, omdat dit de verwachte output zal wissen. Probeer je best te doen om deze taken in één regel pandas-code op te lossen (niet elke vraag kan in één regel worden opgelost, maar veel wel!). LET OP: Veel taken hebben meerdere correcte oplossingsmethoden!**

Omdat er meerdere oplossingsmethoden zijn, kan het zijn dat jouw output er niet helemaal hetzelfde uitziet als in het voorbeeld (bijvoorbeeld '58152' in plaats van 'np.int64(58152)'). Daar moet je geen rekening mee houden. Het zijn de data zelf die belangrijk zijn, niet hoe ze getoond worden.

-----
#### TAAK: Voer de volgende code uit om het bestand "hotel_booking_data.csv" te downloaden en in te lezen. Voel je vrij om het bestand een beetje te verkennen voordat je doorgaat met de rest van de oefening..

In [ ]:
from pathlib import Path
import pandas as pd

URL = 'https://raw.githubusercontent.com/Jef-DS/pandas/main/hotel_booking_data.zip'

HOTEL_DATA_CSV = 'data/hotel_booking_data.csv'
hotel_path = Path(HOTEL_DATA_CSV)
if not hotel_path.exists():
    df = pd.read_csv(URL, compression='zip')
    df.to_csv(HOTEL_DATA_CSV, index=False)

In [ ]:
import pandas as pd
HOTEL_DATA_CSV = 'data/hotel_booking_data.csv'
hotels = pd.read_csv(HOTEL_DATA_CSV)

In [3]:
hotels.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498

In [7]:
hotels.describe(include='all')

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
count,119390,119390.000000,119390.000000,119390.000000,119390,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,...,119390,119390.000000,119390.000000,119390.000000,119390,119390,119390,119390,119390,119390
unique,2,NaN,NaN,NaN,12,NaN,NaN,NaN,NaN,NaN,...,4,NaN,NaN,NaN,3,926,81503,115889,119390,9000
top,City Hotel,NaN,NaN,NaN,August,NaN,NaN,NaN,NaN,NaN,...,Transient,NaN,NaN,NaN,Check-Out,2015-10-21,Michael Johnson,Michael.C@gmail.com,669-792-1661,************3627
freq,79330,NaN,NaN,NaN,13877,NaN,NaN,NaN,NaN,NaN,...,89613,NaN,NaN,NaN,75166,1461,48,6,1,28
mean,NaN,0.370416,104.011416,2016.156554,NaN,27.165173,15.798241,0.927599,2.500302,1.856403,...,NaN,101.831122,0.062518,0.571363,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,0.482918,106.863097,0.707476,NaN,13.605138,8.780829,0.998613,1.908286,0.579261,...,NaN,50.535790,0.245291,0.792798,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,0.000000,0.000000,2015.000000,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,...,NaN,-6.380000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,0.000000,18.000000,2016.000000,NaN,16.000000,8.000000,0.000000,1.000000,2.000000,...,NaN,69.290000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,0.000000,69.000000,2016.000000,NaN,28.000000,16.000000,1.000000,2.000000,2.000000,...,NaN,94.575000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,1.000000,160.000000,2017.000000,NaN,38.000000,23.000000,2.000000,3.000000,2.000000,...,NaN,126.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,1.000000,737.000000,2017.000000,NaN,53.000000,31.000000,19.000000,50.000000,55.000000,...,NaN,5400.000000,8.000000,5.000000,NaN,NaN,NaN,NaN,NaN,NaN

---
**TAAK: Hoeveel rijen zijn er?(1 punt)**

In [4]:
hotels.shape[0]

119390

In [ ]:
# Hier zet je niets

119390

**TAAK: Zijn er ontbrekende gegevens? Zo ja, welke kolom heeft de meeste ontbrekende gegevens?(1 punt)**

In [ ]:
# display(hotels.info())
print(f"'company' kolom missing {hotels['company'].isna().value_counts()[True]} times.")

# ser = hotels.isna().sum().nlargest(1)
# country kolom: ser.index[0], ser.iloc[0]??

'company' kolom missing 112593 times.

In [ ]:
# Find the column with the most NaNs
# Count NaNs per column
nan_counts = hotels.isna().sum() # Pandas Series with counts of NaNs per column
most_nan_column = nan_counts.idxmax()
most_nan_count = nan_counts.max()
print(f"{most_nan_column} kolom missing {most_nan_count} times.")

In [ ]:
# Hier zet je niets

'company' kolom missing 112593 times.

**TAAK: Drop de "company" kolom.(1 punt)**

In [33]:
hotels = hotels.drop(columns='company')
hotels.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 35 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  days_in_waiting_list            119390 non-null  int64
 25  customer_type                   119390 non-null  str
 26  adr                             119390 non-null  float64
 27  required_car_parking_spaces     119390 non-null  int64
 28  total_of_special_requests       119390 non-null  int64
 29  reservation_status              119390 non-null  str
 30  reservation_status_date         119390 non-null  str
 31  name                            119390 non-null  str
 32  email                           119390 non-null  str
 33  phone-number                    119390 non-null  str
 34  credit_card                     119390 non-null  str
dtypes: float64(3), int64(16), str(16)
memory usage: 31.9 MB

In [ ]:
# Hier zet je niets

**TAAK: Hoeveel verschillende meal types zijn er (1 punt)?**

In [34]:
hotels['meal'].nunique()

5

In [ ]:
# Hier zet je niets

5

**TAAK: Wat zijn de 5 meest voorkomende landcodes in de dataset? (2 punten)**

In [40]:
hotels.country.value_counts().head().sort_values(ascending=False)

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
Name: count, dtype: int64

In [ ]:
# Hier zet je niets

PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
Name: country, dtype: int64

**TAAK: Wat is de naam van de persoon die de hoogste ADR (gemiddelde dagtarief) heeft betaald? Hoeveel was dit ADR? (2 punten)**

In [52]:
hotels.loc[hotels.adr == hotels.adr.max()][['adr', 'name']]

          adr           name
48515  5400.0  Daniel Walter

In [ ]:
# Hier zet je niets

          adr           name
48515  5400.0  Daniel Walter

**TAAK: De ADR is het gemiddelde dagtarief voor iemands verblijf in het hotel. Met andere woorden: wat is de gemiddelde ADR over alle hotelverblijven in de dataset? (2 punten)**

In [90]:
round(hotels.adr.mean(), 2)

np.float64(101.83)

In [ ]:
# Hier zet je niets

np.float64(101.83)

**TAAK: Wat is het gemiddelde aantal nachten voor een verblijf in de hele dataset(week en weekend)? Voel je vrij om dit af te ronden op 2 decimalen. (2 punten)**

In [89]:
gemiddelde_aantal_nachten = (hotels.stays_in_weekend_nights + hotels.stays_in_week_nights).mean()
round(gemiddelde_aantal_nachten, 2)

np.float64(3.43)

In [ ]:
# Hier schrijf je niets

np.float64(3.43)

**TAAK: Wat zijn de gemiddelde totale kosten voor een verblijf in de dataset? Niet de gemiddelde dagelijkse kosten, maar de *totale verblijfskosten*. (Je zult zelf de totale kosten moeten berekenen door gebruik te maken van ADR en het aantal week- en weekendnachten). Voel je vrij om dit af te ronden op 2 decimalen.(3 punten)**

In [91]:
totale_verbrijfskost = hotels.adr * (hotels.stays_in_weekend_nights + hotels.stays_in_week_nights)
round(totale_verbrijfskost.mean(), 2)

np.float64(357.85)

In [ ]:
# Hier zet je niets

np.float64(357.85)

**TAAK: Wat zijn de namen en e-mailadressen van mensen die precies 5 "Speciale Verzoeken" hebben gedaan?(3 punten)**

In [50]:
hotels[hotels.total_of_special_requests == 5][['name', 'email']]

                          name                          email
7860             Amanda Harper           Amanda.H66@yahoo.com
11125            Laura Sanders      Sanders_Laura@hotmail.com
14596              Tommy Ortiz            Tommy_O@hotmail.com
14921           Gilbert Miller         Miller.Gilbert@aol.com
14922           Timothy Torres         TTorres@protonmail.com
24630          Jennifer Weaver             Jennifer_W@aol.com
27288           Crystal Horton             Crystal.H@mail.com
27477           Brittney Burke       Burke_Brittney16@att.com
29906          Cynthia Cabrera    Cabrera.Cynthia@xfinity.com
29949              Sarah Floyd              Sarah_F@gmail.com
32267           Michelle Villa         Michelle.Villa@aol.com
39027           Nichole Hebert       Hebert.Nichole@gmail.com
39129         Lindsey Mckenzie       Lindsey.Mckenzie@att.com
39525           Ashley Edwards       Edwards.Ashley@yahoo.com
70114       Christopher Torres   Torres.Christopher@gmail.com
78819   Mrs. Tara Sullivan DVM           Mrs..DVM@xfinity.com
78820           Michaela Brown          MichaelaBrown@att.com
78822        Kurt Maldonado MD              KMD15@xfinity.com
97072         Jason Richardson               Jason.R@zoho.com
97099             Terri Hurley            THurley@xfinity.com
97261        Mrs. Caitlin Webb             Mrs._W@comcast.net
98410             Holly Arroyo          Arroyo_Holly@mail.com
98674          Denise Campbell             Denise_C@gmail.com
99887            Michael Smith            Michael.S42@aol.com
99888       Dr. Trevor Sellers                  Dr._S@aol.com
101569            Kayla Murphy         Kayla.Murphy@yahoo.com
102061         Taylor Martinez    Taylor.Martinez@hotmail.com
109511          Charles Wilson       Charles_Wilson@yahoo.com
109590           Tyler Allison         Tyler.A@protonmail.com
110082          Matthew Bailey         Matthew_Bailey@aol.com
110083       Charlotte Acevedo        Charlotte_A@verizon.com
111909         Darrell Brennan  Brennan_Darrell51@hotmail.com
111911          Melinda Jensen         MelindaJensen@zoho.com
113915            Terry Arnold          Arnold.Terry@zoho.com
114770             Mary Nguyen     Nguyen.Mary@protonmail.com
114909          Lindsay Cuevas      Lindsay.Cuevas40@mail.com
116455       Cynthia Hernandez   CynthiaHernandez@xfinity.com
116457          Angela Hawkins             Angela_H@gmail.com
118817              Sue Lawson            Sue.L52@comcast.net
119161         Alyssa Richards        Alyssa_Richards@aol.com

In [ ]:
# Hier zet je niets

                          name                          email
7860             Amanda Harper           Amanda.H66@yahoo.com
11125            Laura Sanders      Sanders_Laura@hotmail.com
14596              Tommy Ortiz            Tommy_O@hotmail.com
14921           Gilbert Miller         Miller.Gilbert@aol.com
14922           Timothy Torres         TTorres@protonmail.com
24630          Jennifer Weaver             Jennifer_W@aol.com
27288           Crystal Horton             Crystal.H@mail.com
27477           Brittney Burke       Burke_Brittney16@att.com
29906          Cynthia Cabrera    Cabrera.Cynthia@xfinity.com
29949              Sarah Floyd              Sarah_F@gmail.com
32267           Michelle Villa         Michelle.Villa@aol.com
39027           Nichole Hebert       Hebert.Nichole@gmail.com
39129         Lindsey Mckenzie       Lindsey.Mckenzie@att.com
39525           Ashley Edwards       Edwards.Ashley@yahoo.com
70114       Christopher Torres   Torres.Christopher@gmail.com
78819   Mrs. Tara Sullivan DVM           Mrs..DVM@xfinity.com
78820           Michaela Brown          MichaelaBrown@att.com
78822        Kurt Maldonado MD              KMD15@xfinity.com
97072         Jason Richardson               Jason.R@zoho.com
97099             Terri Hurley            THurley@xfinity.com
97261        Mrs. Caitlin Webb             Mrs._W@comcast.net
98410             Holly Arroyo          Arroyo_Holly@mail.com
98674          Denise Campbell             Denise_C@gmail.com
99887            Michael Smith            Michael.S42@aol.com
99888       Dr. Trevor Sellers                  Dr._S@aol.com
101569            Kayla Murphy         Kayla.Murphy@yahoo.com
102061         Taylor Martinez    Taylor.Martinez@hotmail.com
109511          Charles Wilson       Charles_Wilson@yahoo.com
109590           Tyler Allison         Tyler.A@protonmail.com
110082          Matthew Bailey         Matthew_Bailey@aol.com
110083       Charlotte Acevedo        Charlotte_A@verizon.com
111909         Darrell Brennan  Brennan_Darrell51@hotmail.com
111911          Melinda Jensen         MelindaJensen@zoho.com
113915            Terry Arnold          Arnold.Terry@zoho.com
114770             Mary Nguyen     Nguyen.Mary@protonmail.com
114909          Lindsay Cuevas      Lindsay.Cuevas40@mail.com
116455       Cynthia Hernandez   CynthiaHernandez@xfinity.com
116457          Angela Hawkins             Angela_H@gmail.com
118817              Sue Lawson            Sue.L52@comcast.net
119161         Alyssa Richards        Alyssa_Richards@aol.com

**TAAK: Welk percentage van de hotelverblijven werd geclassificeerd als "terugkerende gasten"? (Baseer dit niet op de naam van de persoon, maar op de kolom is_repeated_guest)(3 punten)**

In [ ]:
# display(hotels.is_repeated_guest.unique())
# omdat het enkel 1 en 0 zijn, kan de mean als aantal / totaal dienen
round(hotels.is_repeated_guest.mean() * 100, 2)

np.float64(3.19)

In [ ]:
# Hier zet je niets

np.float64(3.19)

**TAAK: Wat zijn de 5 meest voorkomende achternamen in de dataset? Bonus: Kun je dit in één regel pandas-code uitzoeken? (Voor de eenvoud beschouw een titel zoals MD als een achternaam, bijvoorbeeld Caroline Conley MD kan worden gezegd dat ze de achternaam MD heeft)(4 punten)**

In [ ]:
hotels['name'].str.rsplit(" ").str[1].value_counts().head().sort_values(ascending=False)
# hotels.name.str.split().str[-1].value_counts(ascending=False).head()
# str.rsplit(n=1).str[-1]

name
Smith       2510
Johnson     1998
Williams    1628
Jones       1441
Brown       1433
Name: count, dtype: int64

In [ ]:
# Hier zet je niets

name
Smith       2503
Johnson     1990
Williams    1618
Jones       1434
Brown       1423
Name: count, dtype: int64

**TAAK: Wat zijn de namen van de mensen die het hoogste aantal kinderen en baby's hebben geboekt voor hun verblijf? Toon de naam, het totaal aantal kinderen, het aantal kinderen en het aantal babies (Maak je geen zorgen als ze hebben geannuleerd, neem alleen het aantal mensen in aanmerking dat bij de reservering is opgegeven) (4 punten)**

In [85]:
hotels['total_kids'] = hotels['children'] + hotels['babies']
hotels[['name', 'total_kids', 'children', 'babies']].sort_values('total_kids', ascending=False).head(2)

                  name  total_kids  children  babies
328      Jamie Ramirez        10.0      10.0       0
46619  Nicholas Parker        10.0       0.0      10

In [ ]:
# Hier zet je niets

                  name  total_kids  children  babies
328      Jamie Ramirez        10.0      10.0       0
46619  Nicholas Parker        10.0       0.0      10

**TAAK: Wat zijn de 3 meest voorkomende netnummers (area code) in de telefoonnummers? (Area code zijn de eerste 3 cijfers) (4 punten)**

In [ ]:
hotels['phone-number'].str[:3].value_counts().sort_values(ascending=False).head(3)

phone-number
799    168
185    167
541    166
Name: count, dtype: int64

In [ ]:
# Hier zet je niets

phone-number
799    168
185    167
541    166
Name: count, dtype: int64

**TAAK: Hoeveel aankomsten vonden plaats tussen de 1e en de 15e van de maand (inclusief de 1e en 15e)? (4 punten)**

In [ ]:
hotels.loc[(hotels.arrival_date_day_of_month >= 1) & (hotels.arrival_date_day_of_month <= 15)].shape[0]
# hotels.loc[(hotels.arrival_date_day_of_month <= 15)].shape[0]

58152

In [ ]:
# Hier zet je niets

58152